#+title: Hugo Blog Posts
#+author: Cody Edwards
#+hugo_base_dir: ../
#+startup: overview

* DONE Fragments: Trailer Park Drama                            :fragments:
CLOSED: [2026-04-04 Sat 16:17]
:PROPERTIES:
:EXPORT_FILE_NAME: 2026-04-04-trailer-trash
:END:

When I was 5 or 6, my family briefly lived in a trailer park in
southern New Mexico. I don't remember why we were living
there. Probably to run away from something or someone, usually bill
collectors or repo men. It was easier to do that back then.

I was outside playing with the neighborhood kids. We ran around and
raised hell. At some point we rested at one of those big, wooden
picnic tables at the center of the courtyard. We talked for a while
and began busting each other's balls. One of the kids took it a little
too far and began insulting the others in a cruel way. He turned his
attention toward me, called me names, made fun of my family. He jumped
on top of the table and put his feet in my face. I couldn't take the
abuse anymore, so I grabbed his ankles and yanked as hard as I
could. I guess I hurt him badly because he started crying, tears ran
down his face; his cheeks turned bright red. The door to a nearby
trailer swung open, and a big, balding man came storming over to
us. It was the kid's dad. The dad grabbed his wailing son and yelled
at me to go home.

I don't know why that kid's dad didn't hit me. It was one of those
places at one of those times, and I suppose others in that milieu
wouldn't have thought much of it. Maybe he knew my dad and didn't want
to start any trouble. From my point of view, he got what he
deserved. But I imagine the kid's dad didn't see it that way. He just
saw some little rat harm his child.

Nothing came of it. I never played with those kids again. Soon after,
we moved back to Texas. I guess the coast was clear.


* DONE Proem
CLOSED: [2026-04-02 Thu 18:09]
:PROPERTIES:
:EXPORT_FILE_NAME: 2026-04-02-proem
:END:

I will be honest here: I set up this blog because I was curious
about how to set up a static blog using GitHub as a host. This came to
fruition out of some technical desire. Beyond that, there is no plan
going forward.

The name /Veblenia/ is derived from Veblenian, i.e. someone who adheres,
in whole or in part, to the institutional economics of [[https://en.wikipedia.org/wiki/Thorstein_Veblen][Thorstein
Veblen]]. He was a fascinating character, and it would be well worth
your time read up on him.

It has been claimed by some that I made a typo when registering the
domain. That is false. That is slander. And I deny it.

Regardless, I am excited about what I can do with this space. Maybe a
story! Maybe a recipe! Maybe a detailed accounting of all the slights,
real or imagined, that have been directed toward me. We shall see.
