#+title: Hugo Blog Posts
#+author: Cody Edwards
#+hugo_base_dir: ../
#+startup: overview

* DONE Techlet: Find how much space certain file types take up :techlet:linux:
CLOSED: [2026-04-26 Sun 21:39]
:PROPERTIES:
:EXPORT_FILE_NAME: 2026-04-26-use-find-file-types
:END:

I am pretty sloppy with my file organization. Usually, I just store
things where I think they would be useful at that point in time, not
necessarily where they logically belong. Eventually, I get curious of
how many of a particular file type I have and how much space they are
taking up. Below is a convoluted shell command that searches the home
directory for every file with a particular extension and displays how
many of that type there are and how much space they're taking up.
   
#+begin_src shell 
find ~ -type f -name "*.epub" -print0 \
| xargs -0 -r du -k \
| awk '{
      total+=$1
    }

    END {
      printf("\nTotal files: %d\nTotal Size: %.1f MB\n", NR, total/1024)
    }
  '
#+end_src

1. Find searches the home directory recursively for files ending with,
   in this example, the .epub extension.
2. xargs then passes the results from find to the disk usage utility,
   which calculates the size of each file in kilobytes.
3. Finally, awk sums the size of each file and outputs a nicely
   formatted table with the total size presented in megabytes.

#+begin_example
Total files: 5
Total Size: 11.9 MB
#+end_example

Like I said, it's a bit much. I suppose this could be dumped into a
shell script with the file extension as a positional parameter,
e.g. =./find-ext.sh epub=.

* 

* Attestation: A Car Crash
:PROPERTIES:
:EXPORT_FILE_NAME: 2026-04-05-witness-car-crash
:END:


* DONE Notelet: Christina Hendricks, DJ                     :notelet:music:
CLOSED: [2026-04-05 Sun 00:58]
:PROPERTIES:
:EXPORT_FILE_NAME: 2026-04-05-notelet-hendricks
:END:

Christina Hendricks performed a [[https://consequence.net/2026/04/christina-hendricks-dj-set-san-diego/][four hour DJ set]] at a San Diego bar
the other night, which consisted of primarily shoegaze and dream pop,
such as Slowdive and Japanese Breakfast and Cocteau Twins. She has
great taste.

* DONE Fragment: At A Trailer Park                              :fragments:
CLOSED: [2026-04-04 Sat 16:17]
:PROPERTIES:
:EXPORT_FILE_NAME: 2026-04-04-trailer-trash
:END:

When I was 5 or 6, my family briefly lived in a trailer park in
southern New Mexico. I don't remember why we were living
there. Probably to run away from something or someone, usually bill
collectors or repo men. It was easier to do that back then.

I was outside playing with the neighborhood kids. We ran around and
raised hell. At some point we rested at one of those big, wooden
picnic tables at the center of the courtyard. We talked for a while
and began busting each other's balls. One of the kids took it a little
too far and began cruelly insulting the others. He turned his
attention to me, called me names, made fun of my family. He jumped on
top of the table and put his feet in my face. The anger welled up
inside me and I saw stars. I couldn't take the abuse anymore. I grabbed
his ankles and yanked as hard as I could. The kid's body slammed
against the picnic table, and he made a loud thunk sound on
impact--a sound that sound still resonates inside me to this day.

I guess I hurt him pretty bad because he started crying, tears ran
down his face; his cheeks turned bright red. He wailed and
wailed. Snot bubbled from his nose. The door to a nearby trailer swung
open, and a big, balding man came storming over to us. It was the
kid's dad. The dad grabbed his wailing son and yelled at me to go
home.

I don't know why that kid's dad didn't hit me. It was one of those
places at one of those times, and I suppose others in that milieu
wouldn't have thought much of a grown man beating a child, had the
child deserved it. Maybe he knew my dad and didn't want to start any
trouble. Can't say one way or the other. Can't really say why I wonder
about it at all.

Nothing came of it. I never played with those kids again. Soon after,
we moved back to Texas. I guess the coast was clear.

* DONE Proem
CLOSED: [2026-04-02 Thu 18:09]
:PROPERTIES:
:EXPORT_FILE_NAME: 2026-04-02-proem
:END:

I will be honest here: I set up this blog because I was curious
about how to set up a static blog using GitHub as a host. This came to
fruition out of some technical desire. Beyond that, there is no plan
going forward.

The name /Veblenia/ is derived from Veblenian, i.e. someone who adheres,
in whole or in part, to the institutional economics of [[https://en.wikipedia.org/wiki/Thorstein_Veblen][Thorstein
Veblen]]. He was a fascinating character, and it would be well worth
your time read up on him.

It has been claimed by some that I made a typo when registering the
domain. That is false. That is slander. And I deny it.

Regardless, I am excited about what I can do with this space. Maybe a
story! Maybe a recipe! Maybe a detailed accounting of all the slights,
real or imagined, that have been directed toward me. We shall see.


